### ISSUE TITLE
Dependency on importlib module

### ISSUE THREAD

**Issue by griffin-h** [fred3m/toyz#10]
`toyz` seems to depend on `importlib`, but `importlib` is not installed along with `toyz`.

```
Loading dependencies, please wait...
Traceback (most recent call last):
  File "/usr/bin/toyz", line 5, in <module>
    pkg_resources.run_script('toyz==0.0.dev', 'toyz')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/toyz-0.0.dev-py2.6.egg/EGG-INFO/scripts/toyz", line 7, in <module>
    from toyz.web.app import init_web_app
  File "/usr/lib/python2.6/site-packages/toyz-0.0.dev-py2.6.egg/toyz/__init__.py", line 1, in <module>
    from toyz import web
  File "/usr/lib/python2.6/site-packages/toyz-0.0.dev-py2.6.egg/toyz/web/__init__.py", line 1, in <module>
    from toyz.web import app
  File "/usr/lib/python2.6/site-packages/toyz-0.0.dev-py2.6.egg/toyz/web/app.py", line 12, in <module>
    import importlib
```

Running `pip install importlib` fixes the broken dependency, but it would be nice if this happened automatically.

**Comment by fred3m** [comment]
You're right, I thought importlib was part of the standard library. It has been added to the installation requirements, thanks for letting me know.
