### ISSUE TITLE
UnboundLocalError in first time setup script

### ISSUE THREAD

**Issue by cdeil** [fred3m/toyz#8]
I'm trying to follow the instructions at http://fred3m.github.io/toyz/getting_started.html#first-time-setup, but I'm getting this error:
```
$ toyz 
Loading dependencies, please wait...
Server root directory: /Users/deil/Library/Python/2.7/lib/python/site-packages/toyz-0.0.dev-py2.7.egg/toyz

Toyz: First Time Setup
----------------------

Create new Toyz configuration in '/private/tmp'? /tmp/toys-config
Traceback (most recent call last):
  File "/Users/deil/Library/Python/2.7/bin/toyz", line 5, in <module>
    pkg_resources.run_script('toyz==0.0.dev', 'toyz')
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/toyz-0.0.dev-py2.7.egg/EGG-INFO/scripts/toyz", line 9, in <module>
    init_web_app()
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/toyz-0.0.dev-py2.7.egg/toyz/web/app.py", line 564, in init_web_app
    toyz_app = ToyzWebApp()
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/toyz-0.0.dev-py2.7.egg/toyz/web/app.py", line 404, in __init__
    self.toyz_settings = core.ToyzSettings(root_path)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/toyz-0.0.dev-py2.7.egg/toyz/utils/core.py", line 599, in __init__
    self.first_time_setup(config_root_path)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/toyz-0.0.dev-py2.7.egg/toyz/utils/core.py", line 656, in first_time_setup
    "Create new Toyz configuration in '{0}'? ".format(self.config.root_path)):
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/toyz-0.0.dev-py2.7.egg/toyz/utils/core.py", line 91, in get_bool
    "(true/false, yes/no, t/f, y/n)".format(bool_str))
UnboundLocalError: local variable 'bool_str' referenced before assignment
```
@fred3m – Can you reproduce / fix this?

**Comment by fred3m** [comment]
Sorry this wasn't clear, I'll have to fix the docs and the prompt. When it says "Create new Toyz configuration in ..." it's expecting something like 'yes', 'no', 'true', 'false', 'y', 'n', etc. It uses a command almost like a regex to try and convert your response to a boolean. So just enter 'n' and let me know if this works.

**Comment by cdeil** [comment]
Ah, OK, that worked.

Now after logging in I'm getting this error:
![screen shot 2015-04-20 at 22 45 18](https://cloud.githubusercontent.com/assets/852409/7240105/fe1ebccc-e7ae-11e4-886d-add08c87cda9.png)
https://gist.github.com/cdeil/d51935a655673ddc9df2

**Comment by fred3m** [comment]
Try to run the code and wait a minute, then log on to the webpage. If it
still doesn't work hit "refresh" in your browser. This is a bug I've been
trying to figure out how best to fix. The issue is that when I start the IO
loop in Tornado there seems to be a bit of a lag (sometimes) before the web
application is completely up and running, so you're trying to log onto the
server before it's completely up. I'm used to hitting "refresh" for now but
this is one of those bugs I mentioned this afternoon that I want to fix
before I release the first version on Pypy.

**Comment by fred3m** [comment]
Can I close this ticket?

**Comment by cdeil** [comment]
Yes, this issue is fixed. Thanks!
