### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by griffin-h** [fred3m/toyz#9]
After installing and trying to run `toyz` for the first time, I get this syntax error.

```
Loading dependencies, please wait...
Traceback (most recent call last):
  File "/usr/bin/toyz", line 5, in <module>
    pkg_resources.run_script('toyz==0.0.dev', 'toyz')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/toyz-0.0.dev-py2.6.egg/EGG-INFO/scripts/toyz", line 7, in <module>
    from toyz.web.app import init_web_app
  File "/usr/lib/python2.6/site-packages/toyz-0.0.dev-py2.6.egg/toyz/__init__.py", line 1, in <module>
    from toyz import web
  File "/usr/lib/python2.6/site-packages/toyz-0.0.dev-py2.6.egg/toyz/web/__init__.py", line 1, in <module>
    from toyz.web import app
  File "/usr/lib/python2.6/site-packages/toyz-0.0.dev-py2.6.egg/toyz/web/app.py", line 24, in <module>
    from toyz.utils import core
  File "/usr/lib/python2.6/site-packages/toyz-0.0.dev-py2.6.egg/toyz/utils/__init__.py", line 11, in <module>
    from toyz.utils import io
  File "/usr/lib/python2.6/site-packages/toyz-0.0.dev-py2.6.egg/toyz/utils/io.py", line 584
    file_options = {k:v for k,v in file_options.items() if k not in remove}
                          ^
SyntaxError: invalid syntax
```

**Comment by fred3m** [comment]
It looks like you're running Python 2.6, which is not supported by Toyz. The error occurs because dictionary comprehensions aren't supported in Python 2.6.

If running Toyz in Python 2.6 is essential to you and you're like to help make it Python 2.6 compatible I'd be happy to help. Otherwise I recommend using virtualenv or anaconda to run a Python 2.7 environment on your computer.

**Comment by griffin-h** [comment]
Ahh, thanks, I should have noticed this myself. I will try again with Python 2.7.
